import type { VendorLogoPreset } from "./types";

export type VendorLogoPresetDefaults = {
  label: string;
  description: string;
  word1Label: string;
  word1Hint: string;
  word1Default: string;
  word2Label: string;
  word2Hint: string;
  word2Default: string;
  primary: string;
  secondary: string;
  accent: string;
  tertiary: string;
  highlight: string;
  background: string;
};

/** Colorful South Asian monogram presets — one large initial, 5+ elegant palette colors each. */
export const VENDOR_LOGO_PRESET_DEFAULTS: Record<VendorLogoPreset, VendorLogoPresetDefaults> = {
  "lotus-grace": {
    label: "Lotus Monogram",
    description:
      "Rani maroon, antique gold, gulabi pink, sindoor orange & mehndi green lotus petals.",
    word1Label: "Your brand initial",
    word1Hint: "One letter (e.g. A for Anaya, M for Maruthi)",
    word1Default: "A",
    word2Label: "Initial",
    word2Hint: "Same as your letter",
    word2Default: "A",
    primary: "#8B1538",
    secondary: "#C9A227",
    accent: "#E91E8C",
    tertiary: "#FF6B35",
    highlight: "#6B9E3E",
    background: "#FFF8F0",
  },
  "peacock-royal": {
    label: "Peacock Monogram",
    description:
      "Peacock blue, zari gold, emerald, royal purple & magenta eye-spots around your initial.",
    word1Label: "Your brand initial",
    word1Hint: "One letter (e.g. M for Mayura)",
    word1Default: "M",
    word2Label: "Initial",
    word2Hint: "Same as your letter",
    word2Default: "M",
    primary: "#0E4D64",
    secondary: "#D4AF37",
    accent: "#1B998B",
    tertiary: "#7B2CBF",
    highlight: "#EC4899",
    background: "#ECFEFF",
  },
  "mandala-gold": {
    label: "Mandala Monogram",
    description:
      "Kumkum red, kesari saffron, haldi gold, fuchsia & turquoise mandala rings.",
    word1Label: "Your brand initial",
    word1Hint: "One letter (e.g. D for Devi)",
    word1Default: "D",
    word2Label: "Initial",
    word2Hint: "Same as your letter",
    word2Default: "D",
    primary: "#B91C1C",
    secondary: "#EA580C",
    accent: "#FBBF24",
    tertiary: "#DB2777",
    highlight: "#0891B2",
    background: "#FFF7ED",
  },
  "silk-emblem": {
    label: "Bandhani Monogram",
    description:
      "Royal purple, bandhani pink, marigold, emerald & amber tie-dye dots.",
    word1Label: "Your brand initial",
    word1Hint: "One letter (e.g. R for Resham)",
    word1Default: "R",
    word2Label: "Initial",
    word2Hint: "Same as your letter",
    word2Default: "R",
    primary: "#6B21A8",
    secondary: "#DB2777",
    accent: "#F97316",
    tertiary: "#059669",
    highlight: "#EAB308",
    background: "#FAF5FF",
  },
  "temple-arch": {
    label: "Heritage Monogram",
    description:
      "Terracotta, temple jade, saffron tilak, rose & Krishna blue heritage arch.",
    word1Label: "Your brand initial",
    word1Hint: "One letter (e.g. G for Gopuram)",
    word1Default: "G",
    word2Label: "Initial",
    word2Hint: "Same as your letter",
    word2Default: "G",
    primary: "#92400E",
    secondary: "#047857",
    accent: "#F59E0B",
    tertiary: "#BE123C",
    highlight: "#2563EB",
    background: "#FFFBEB",
  },
  "rangoli-star": {
    label: "Rangoli Star",
    description: "Vermillion, turmeric, cobalt, magenta & leaf green eight-point Diwali star.",
    word1Label: "Your brand initial",
    word1Hint: "One letter (e.g. S for Star)",
    word1Default: "S",
    word2Label: "Initial",
    word2Hint: "Same as your letter",
    word2Default: "S",
    primary: "#DC2626",
    secondary: "#FACC15",
    accent: "#2563EB",
    tertiary: "#C026D3",
    highlight: "#16A34A",
    background: "#FFF1F2",
  },
  "diya-lamp": {
    label: "Diya Lamp",
    description: "Deep amber, flame gold, rose, teal & violet festive diya glow.",
    word1Label: "Your brand initial",
    word1Hint: "One letter (e.g. D for Deepak)",
    word1Default: "D",
    word2Label: "Initial",
    word2Hint: "Same as your letter",
    word2Default: "D",
    primary: "#B45309",
    secondary: "#FBBF24",
    accent: "#F43F5E",
    tertiary: "#0D9488",
    highlight: "#7C3AED",
    background: "#FFFBEB",
  },
  "jasmine-wreath": {
    label: "Jasmine Wreath",
    description: "Ivory blossom, malli green, gold, coral & sky blue garland ring.",
    word1Label: "Your brand initial",
    word1Hint: "One letter (e.g. J for Jasmine)",
    word1Default: "J",
    word2Label: "Initial",
    word2Hint: "Same as your letter",
    word2Default: "J",
    primary: "#15803D",
    secondary: "#FDE68A",
    accent: "#F472B6",
    tertiary: "#38BDF8",
    highlight: "#FB7185",
    background: "#F0FDF4",
  },
  "paisley-curve": {
    label: "Paisley Curve",
    description: "Indigo, crimson, saffron, emerald & copper classic boteh swirls.",
    word1Label: "Your brand initial",
    word1Hint: "One letter (e.g. P for Paisley)",
    word1Default: "P",
    word2Label: "Initial",
    word2Hint: "Same as your letter",
    word2Default: "P",
    primary: "#1E3A8A",
    secondary: "#BE123C",
    accent: "#F97316",
    tertiary: "#059669",
    highlight: "#B45309",
    background: "#EFF6FF",
  },
  "kite-sankranti": {
    label: "Kite Festival",
    description: "Cerulean, hot pink, lime, tangerine & violet Makar Sankranti kite.",
    word1Label: "Your brand initial",
    word1Hint: "One letter (e.g. K for Kite)",
    word1Default: "K",
    word2Label: "Initial",
    word2Hint: "Same as your letter",
    word2Default: "K",
    primary: "#0284C7",
    secondary: "#EC4899",
    accent: "#84CC16",
    tertiary: "#FB923C",
    highlight: "#8B5CF6",
    background: "#F0F9FF",
  },
  "henna-scroll": {
    label: "Henna Scroll",
    description: "Mehndi brown, henna orange, rose, peacock & gold corner scrollwork.",
    word1Label: "Your brand initial",
    word1Hint: "One letter (e.g. H for Henna)",
    word1Default: "H",
    word2Label: "Initial",
    word2Hint: "Same as your letter",
    word2Default: "H",
    primary: "#78350F",
    secondary: "#EA580C",
    accent: "#E11D48",
    tertiary: "#0F766E",
    highlight: "#CA8A04",
    background: "#FFF7ED",
  },
  "marigold-ring": {
    label: "Marigold Ring",
    description: "Marigold orange, genda yellow, crimson, teal & plum flower crown.",
    word1Label: "Your brand initial",
    word1Hint: "One letter (e.g. M for Marigold)",
    word1Default: "M",
    word2Label: "Initial",
    word2Hint: "Same as your letter",
    word2Default: "M",
    primary: "#EA580C",
    secondary: "#EAB308",
    accent: "#DC2626",
    tertiary: "#0891B2",
    highlight: "#9333EA",
    background: "#FFFBEB",
  },
  "chakra-wheel": {
    label: "Chakra Wheel",
    description: "Navy, saffron, white accent, green & amber Ashoka-inspired wheel.",
    word1Label: "Your brand initial",
    word1Hint: "One letter (e.g. C for Chakra)",
    word1Default: "C",
    word2Label: "Initial",
    word2Hint: "Same as your letter",
    word2Default: "C",
    primary: "#1E40AF",
    secondary: "#F97316",
    accent: "#EF4444",
    tertiary: "#16A34A",
    highlight: "#F59E0B",
    background: "#F8FAFC",
  },
  "hex-kolam": {
    label: "Hex Kolam",
    description: "Rice-white lines with ruby, cyan, violet, gold & coral hex geometry.",
    word1Label: "Your brand initial",
    word1Hint: "One letter (e.g. N for Kolam)",
    word1Default: "N",
    word2Label: "Initial",
    word2Hint: "Same as your letter",
    word2Default: "N",
    primary: "#BE185D",
    secondary: "#06B6D4",
    accent: "#7C3AED",
    tertiary: "#F59E0B",
    highlight: "#F97316",
    background: "#FFFAFA",
  },
  "elephant-emblem": {
    label: "Elephant Emblem",
    description: "Royal red, gold caparison, jade, indigo & rose festive haathi motif.",
    word1Label: "Your brand initial",
    word1Hint: "One letter (e.g. E for Elephant)",
    word1Default: "E",
    word2Label: "Initial",
    word2Hint: "Same as your letter",
    word2Default: "E",
    primary: "#991B1B",
    secondary: "#D97706",
    accent: "#047857",
    tertiary: "#4338CA",
    highlight: "#DB2777",
    background: "#FEF2F2",
  },
};

export const VENDOR_LOGO_PRESET_OPTIONS = Object.entries(VENDOR_LOGO_PRESET_DEFAULTS).map(
  ([value, defaults]) => ({
    value: value as VendorLogoPreset,
    label: defaults.label,
  }),
);
