import type { HappyBannerPreset } from "./types";

export type HappyBannerPresetDefaults = {
  label: string;
  description: string;
  word1Label: string;
  word1Hint: string;
  word1Default: string;
  word2Label: string;
  word2Hint: string;
  word2Default: string;
  eyebrowText: string;
  secondaryWord: string;
  ctaLabel: string;
  discountPrefix: string;
  discountSuffix: string;
  backgroundColor: string;
  accentYellow: string;
  accentPink: string;
  showEyebrow: boolean;
  showCta: boolean;
};

export const HAPPY_BANNER_PRESET_DEFAULTS: Record<HappyBannerPreset, HappyBannerPresetDefaults> = {
  "mega-sale": {
    label: "Mega Sale",
    description: "Bold blue promo with circular discount badge.",
    word1Label: "Word 1",
    word1Hint: "Main headline (e.g. MEGA, SUMMER)",
    word1Default: "MEGA",
    word2Label: "Word 2",
    word2Hint: "Discount number before % (e.g. 50, 35)",
    word2Default: "50",
    eyebrowText: "LIMITED TIME ONLY",
    secondaryWord: "SALE",
    ctaLabel: "SHOP NOW",
    discountPrefix: "UP TO",
    discountSuffix: "OFF",
    backgroundColor: "#1b2db8",
    accentYellow: "#ffd400",
    accentPink: "#ff2d9a",
    showEyebrow: true,
    showCta: true,
  },
  "summer-sale": {
    label: "Summer Big Sale",
    description: "Tropical green layout with script subtitle and offer bar.",
    word1Label: "Word 1",
    word1Hint: "Season headline (e.g. SUMMER, SPRING)",
    word1Default: "SUMMER",
    word2Label: "Word 2",
    word2Hint: "Discount number before % (e.g. 50, 40)",
    word2Default: "50",
    eyebrowText: "",
    secondaryWord: "Big Sale",
    ctaLabel: "",
    discountPrefix: "DISCOUNT UP TO",
    discountSuffix: "OFF",
    backgroundColor: "#2f5536",
    accentYellow: "#9fd356",
    accentPink: "#7ec8e3",
    showEyebrow: false,
    showCta: false,
  },
  "hue-editorial": {
    label: "Hue Are You Editorial",
    description: "Yellow editorial split layout — headline + website line.",
    word1Label: "Headline",
    word1Hint: "Main headline (e.g. HUE ARE YOU?)",
    word1Default: "HUE ARE YOU?",
    word2Label: "Website",
    word2Hint: "Store URL line (e.g. TALBOTS.COM)",
    word2Default: "TALBOTS.COM",
    eyebrowText: "",
    secondaryWord: "",
    ctaLabel: "SHOP NOW ›",
    discountPrefix: "",
    discountSuffix: "",
    backgroundColor: "#f5d030",
    accentYellow: "#8b1538",
    accentPink: "#e84b73",
    showEyebrow: false,
    showCta: true,
  },
  "tropical-hot-sale": {
    label: "Tropical Hot Sale",
    description: "Beige tropical promo — fixed HOT script, Word 1 headline, Word 2 discount %.",
    word1Label: "Headline",
    word1Hint: "Main sale line without HOT (e.g. SUMMER SALE)",
    word1Default: "SUMMER SALE",
    word2Label: "Word 2",
    word2Hint: "Discount number before % (e.g. 50, 40)",
    word2Default: "50",
    eyebrowText: "SPECIAL OFFER",
    secondaryWord: "HOT",
    ctaLabel: "SHOP NOW",
    discountPrefix: "UP TO",
    discountSuffix: "OFF",
    backgroundColor: "#f5f0e8",
    accentYellow: "#1a5c32",
    accentPink: "#e31c23",
    showEyebrow: true,
    showCta: true,
  },
  "new-arrivals": {
    label: "New Arrivals",
    description: "Blush boutique split — headline + collection tagline, perfect for fresh drops.",
    word1Label: "Headline",
    word1Hint: "Main line (e.g. NEW IN, JUST DROPPED)",
    word1Default: "NEW IN",
    word2Label: "Collection tagline",
    word2Hint: "Subline (e.g. SPRING COLLECTION)",
    word2Default: "SPRING COLLECTION",
    eyebrowText: "JUST ARRIVED",
    secondaryWord: "",
    ctaLabel: "SHOP NEW",
    discountPrefix: "",
    discountSuffix: "",
    backgroundColor: "#fce7f3",
    accentYellow: "#831843",
    accentPink: "#f472b6",
    showEyebrow: true,
    showCta: true,
  },
  "ethnic-festive": {
    label: "Ethnic Festive",
    description: "Maroon & gold festive frame — sarees, lehengas & celebration wear.",
    word1Label: "Headline",
    word1Hint: "Main line (e.g. FESTIVE, WEDDING)",
    word1Default: "FESTIVE",
    word2Label: "Category tagline",
    word2Hint: "Subline (e.g. SAREES & LEHENGAS)",
    word2Default: "SAREES & LEHENGAS",
    eyebrowText: "LIMITED EDITION",
    secondaryWord: "EDIT",
    ctaLabel: "SHOP ETHNIC",
    discountPrefix: "",
    discountSuffix: "",
    backgroundColor: "#4a0420",
    accentYellow: "#d4af37",
    accentPink: "#fb7185",
    showEyebrow: true,
    showCta: true,
  },
  "flash-sale": {
    label: "Flash Sale",
    description: "Bold fuchsia flash promo — headline + discount % badge.",
    word1Label: "Headline",
    word1Hint: "Sale word (e.g. FLASH, SUPER)",
    word1Default: "FLASH",
    word2Label: "Discount %",
    word2Hint: "Number before % (e.g. 40, 60)",
    word2Default: "40",
    eyebrowText: "24 HOURS ONLY",
    secondaryWord: "SALE",
    ctaLabel: "GRAB NOW",
    discountPrefix: "UP TO",
    discountSuffix: "OFF",
    backgroundColor: "#be185d",
    accentYellow: "#fde047",
    accentPink: "#ffffff",
    showEyebrow: true,
    showCta: true,
  },
  "bridal-edit": {
    label: "Bridal Edit",
    description: "Rose-gold bridal boutique — elegant wedding & reception wear.",
    word1Label: "Headline",
    word1Hint: "Main line (e.g. BRIDAL, WEDDING)",
    word1Default: "BRIDAL",
    word2Label: "Edit tagline",
    word2Hint: "Subline (e.g. WEDDING EDIT)",
    word2Default: "WEDDING EDIT",
    eyebrowText: "CURATED FOR YOU",
    secondaryWord: "",
    ctaLabel: "EXPLORE",
    discountPrefix: "",
    discountSuffix: "",
    backgroundColor: "#fff1f2",
    accentYellow: "#9f1239",
    accentPink: "#e8b4b8",
    showEyebrow: true,
    showCta: true,
  },
  "linen-edit": {
    label: "Linen Collection",
    description: "Airy sage & cream — breezy summer kurtas & co-ords.",
    word1Label: "Headline",
    word1Hint: "Fabric or season (e.g. LINEN, COTTON)",
    word1Default: "LINEN",
    word2Label: "Tagline",
    word2Hint: "Subline (e.g. SUMMER ESSENTIALS)",
    word2Default: "SUMMER ESSENTIALS",
    eyebrowText: "NEW SEASON",
    secondaryWord: "COLLECTION",
    ctaLabel: "SHOP LINEN",
    discountPrefix: "",
    discountSuffix: "",
    backgroundColor: "#ecfdf5",
    accentYellow: "#065f46",
    accentPink: "#a7f3d0",
    showEyebrow: true,
    showCta: true,
  },
  "kurta-print": {
    label: "Kurta Print",
    description: "Indigo block-print style — everyday & festive kurtas.",
    word1Label: "Headline",
    word1Hint: "Main line (e.g. KURTA, BLOCK PRINT)",
    word1Default: "KURTA",
    word2Label: "Style tagline",
    word2Hint: "Subline (e.g. HAND BLOCK PRINT)",
    word2Default: "HAND BLOCK PRINT",
    eyebrowText: "ARTISAN MADE",
    secondaryWord: "",
    ctaLabel: "SHOP KURTAS",
    discountPrefix: "",
    discountSuffix: "",
    backgroundColor: "#1e3a8a",
    accentYellow: "#fef3c7",
    accentPink: "#93c5fd",
    showEyebrow: true,
    showCta: true,
  },
  "luxury-boutique": {
    label: "Luxury Boutique",
    description: "Black & gold designer edit — premium occasion wear.",
    word1Label: "Headline",
    word1Hint: "Main line (e.g. LUXE, COUTURE)",
    word1Default: "LUXE",
    word2Label: "Tagline",
    word2Hint: "Subline (e.g. DESIGNER PICKS)",
    word2Default: "DESIGNER PICKS",
    eyebrowText: "EXCLUSIVE",
    secondaryWord: "",
    ctaLabel: "DISCOVER",
    discountPrefix: "",
    discountSuffix: "",
    backgroundColor: "#0a0a0a",
    accentYellow: "#d4af37",
    accentPink: "#f5f5f4",
    showEyebrow: true,
    showCta: true,
  },
  "boho-chic": {
    label: "Boho Chic",
    description: "Terracotta & sage free-spirited fashion banner.",
    word1Label: "Headline",
    word1Hint: "Main line (e.g. BOHO, EARTH)",
    word1Default: "BOHO",
    word2Label: "Tagline",
    word2Hint: "Subline (e.g. FREE SPIRITED STYLE)",
    word2Default: "FREE SPIRITED STYLE",
    eyebrowText: "NEW STYLES",
    secondaryWord: "CHIC",
    ctaLabel: "SHOP BOHO",
    discountPrefix: "",
    discountSuffix: "",
    backgroundColor: "#ea580c",
    accentYellow: "#fef3c7",
    accentPink: "#4d7c0f",
    showEyebrow: true,
    showCta: true,
  },
  "clearance-eoss": {
    label: "End of Season",
    description: "High-contrast clearance stripe — headline + discount %.",
    word1Label: "Headline",
    word1Hint: "Sale word (e.g. CLEARANCE, EOSS)",
    word1Default: "CLEARANCE",
    word2Label: "Discount %",
    word2Hint: "Number before % (e.g. 70, 50)",
    word2Default: "70",
    eyebrowText: "END OF SEASON",
    secondaryWord: "SALE",
    ctaLabel: "SHOP DEALS",
    discountPrefix: "UP TO",
    discountSuffix: "OFF",
    backgroundColor: "#18181b",
    accentYellow: "#ef4444",
    accentPink: "#fafafa",
    showEyebrow: true,
    showCta: true,
  },
  "handloom-heritage": {
    label: "Handloom Heritage",
    description: "Warm ochre woven texture — sarees & handloom specials.",
    word1Label: "Headline",
    word1Hint: "Main line (e.g. HANDLOOM, HERITAGE)",
    word1Default: "HANDLOOM",
    word2Label: "Tagline",
    word2Hint: "Subline (e.g. WOVEN WITH LOVE)",
    word2Default: "WOVEN WITH LOVE",
    eyebrowText: "CRAFTED IN INDIA",
    secondaryWord: "",
    ctaLabel: "SHOP SAREES",
    discountPrefix: "",
    discountSuffix: "",
    backgroundColor: "#78350f",
    accentYellow: "#fde68a",
    accentPink: "#fcd34d",
    showEyebrow: true,
    showCta: true,
  },
};

export const HAPPY_BANNER_PRESET_OPTIONS = (
  Object.entries(HAPPY_BANNER_PRESET_DEFAULTS) as [HappyBannerPreset, HappyBannerPresetDefaults][]
).map(([value, config]) => ({
  value,
  label: config.label,
}));
