/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    tags: Tag;
    'hero-banners': HeroBanner;
    orders: Order;
    vendors: Vendor;
    roles: Role;
    customers: Customer;
    'variant-types': VariantType;
    'variant-options': VariantOption;
    'vendor-hero-banners': VendorHeroBanner;
    'vendor-templates': VendorTemplate;
    'happy-banners': HappyBanner;
    'vendor-logo-templates': VendorLogoTemplate;
    'potential-vendor-regions': PotentialVendorRegion;
    favorites: Favorite;
    'product-likes': ProductLike;
    'product-comments': ProductComment;
    'social-posts': SocialPost;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'hero-banners': HeroBannersSelect<false> | HeroBannersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    vendors: VendorsSelect<false> | VendorsSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'variant-types': VariantTypesSelect<false> | VariantTypesSelect<true>;
    'variant-options': VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    'vendor-hero-banners': VendorHeroBannersSelect<false> | VendorHeroBannersSelect<true>;
    'vendor-templates': VendorTemplatesSelect<false> | VendorTemplatesSelect<true>;
    'happy-banners': HappyBannersSelect<false> | HappyBannersSelect<true>;
    'vendor-logo-templates': VendorLogoTemplatesSelect<false> | VendorLogoTemplatesSelect<true>;
    'potential-vendor-regions': PotentialVendorRegionsSelect<false> | PotentialVendorRegionsSelect<true>;
    favorites: FavoritesSelect<false> | FavoritesSelect<true>;
    'product-likes': ProductLikesSelect<false> | ProductLikesSelect<true>;
    'product-comments': ProductCommentsSelect<false> | ProductCommentsSelect<true>;
    'social-posts': SocialPostsSelect<false> | SocialPostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'hero-banner-config': HeroBannerConfig;
  };
  globalsSelect: {
    'hero-banner-config': HeroBannerConfigSelect<false> | HeroBannerConfigSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  username?: string | null;
  name?: string | null;
  role: 'user' | 'vendor' | 'admin';
  /**
   * Authentication method used by this user
   */
  oauthProvider?: ('email' | 'google' | 'facebook') | null;
  /**
   * OAuth provider user ID
   */
  oauthId?: string | null;
  /**
   * User avatar URL (from OAuth or uploaded)
   */
  avatar?: string | null;
  /**
   * The vendor/shop this user belongs to. Not used for admin or BDO accounts.
   */
  vendor?: (string | null) | Vendor;
  /**
   * Manage multiple shipping addresses. Set one as default for faster checkout.
   */
  shippingAddresses?:
    | {
        /**
         * e.g., Home, Work, Office
         */
        label: string;
        /**
         * Set as default shipping address
         */
        isDefault?: boolean | null;
        /**
         * Recipient's full name
         */
        fullName: string;
        /**
         * Contact phone number (e.g., +1-555-123-4567)
         */
        phone: string;
        /**
         * Street address, apartment, suite, etc.
         */
        street: string;
        city: string;
        state:
          | 'AL'
          | 'AK'
          | 'AZ'
          | 'AR'
          | 'CA'
          | 'CO'
          | 'CT'
          | 'DE'
          | 'FL'
          | 'GA'
          | 'HI'
          | 'ID'
          | 'IL'
          | 'IN'
          | 'IA'
          | 'KS'
          | 'KY'
          | 'LA'
          | 'ME'
          | 'MD'
          | 'MA'
          | 'MI'
          | 'MN'
          | 'MS'
          | 'MO'
          | 'MT'
          | 'NE'
          | 'NV'
          | 'NH'
          | 'NJ'
          | 'NM'
          | 'NY'
          | 'NC'
          | 'ND'
          | 'OH'
          | 'OK'
          | 'OR'
          | 'PA'
          | 'RI'
          | 'SC'
          | 'SD'
          | 'TN'
          | 'TX'
          | 'UT'
          | 'VT'
          | 'VA'
          | 'WA'
          | 'WV'
          | 'WI'
          | 'WY'
          | 'DC';
        /**
         * 5-digit ZIP code or ZIP+4 format (e.g., 12345 or 12345-6789)
         */
        zipcode: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Vendors/Sellers in the marketplace
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors".
 */
export interface Vendor {
  id: string;
  /**
   * Business/Vendor name
   */
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name)
   */
  slug: string;
  /**
   * Vendor description/bio
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Vendor logo image (custom upload)
   */
  logo?: (string | null) | Media;
  /**
   * Whether the storefront uses a custom uploaded logo or a logo template
   */
  logoSource?: ('upload' | 'template') | null;
  /**
   * Vendor-selected logo design and two customizable keywords
   */
  logoTemplate?: {
    selectedTemplate?: (string | null) | VendorLogoTemplate;
    /**
     * Primary brand word (e.g. ANAYA, MARUTHI)
     */
    word1?: string | null;
    /**
     * Tagline word (e.g. SILKS, COLLECTION)
     */
    word2?: string | null;
  };
  /**
   * Vendor cover/banner image (fallback if hero banner not configured)
   */
  coverImage?: (string | null) | Media;
  /**
   * Vendor-selected Happy Banner design and editable words.
   */
  happyBanner?: {
    /**
     * Banner design shown on the vendor storefront
     */
    selectedBanner?: (string | null) | HappyBanner;
    /**
     * Primary headline word (e.g. MEGA, SUMMER)
     */
    word1?: string | null;
    /**
     * Discount number shown before % (e.g. 50, 35)
     */
    word2?: string | null;
  };
  /**
   * Configure a custom hero banner for your vendor page. If not configured, the cover image will be used.
   */
  heroBanner?: {
    /**
     * Main title displayed on the hero banner (e.g., 'Welcome to [Vendor Name]')
     */
    title?: string | null;
    /**
     * Optional subtitle text displayed below the title
     */
    subtitle?: string | null;
    /**
     * Background image for the hero banner (recommended: 1920x500px). If not set, a gradient will be used.
     */
    backgroundImage?: (string | null) | Media;
    /**
     * Select products to display in the hero banner (4-6 products recommended). Only your own products can be selected.
     */
    products?: (string | Product)[] | null;
    /**
     * Only active hero banners will be displayed on your vendor page
     */
    isActive?: boolean | null;
    /**
     * Display order (lower numbers appear first, if multiple banners exist)
     */
    order?: number | null;
  };
  /**
   * Business email address
   */
  email: string;
  /**
   * Business phone number
   */
  phone?: string | null;
  /**
   * Business website URL
   */
  website?: string | null;
  /**
   * Your Instagram, Facebook page, and WhatsApp group. Vendors and Evega staff can update these for digital marketing.
   */
  socialChannels?: {
    /**
     * Instagram profile or page URL (e.g. https://instagram.com/yourstore)
     */
    socialInstagram?: string | null;
    /**
     * Last promotional post on this Instagram account (not profile URL edits)
     */
    socialInstagramLastPostedAt?: string | null;
    /**
     * Facebook page URL
     */
    socialFacebook?: string | null;
    /**
     * Last promotional post on this Facebook page
     */
    socialFacebookLastPostedAt?: string | null;
    /**
     * WhatsApp group invite link (https://chat.whatsapp.com/…)
     */
    socialWhatsAppGroup?: string | null;
    /**
     * Last promotional post in this WhatsApp group
     */
    socialWhatsAppGroupLastPostedAt?: string | null;
    /**
     * Posting preferences, handles, or other notes for marketing
     */
    socialNotes?: string | null;
  };
  /**
   * Facebook groups, Instagram pages, and other channels where you or Evega promote this store. Vendors and staff can add or update entries.
   */
  marketingChannels?:
    | {
        platform: 'facebook-group' | 'instagram-page' | 'whatsapp-group' | 'other';
        /**
         * e.g. "Desi Fashion Deals", "Charlotte Saree Lovers"
         */
        name: string;
        /**
         * Link to the group or page
         */
        url: string;
        /**
         * State or metro area (optional)
         */
        region?: string | null;
        /**
         * Who is in this channel and any rules for posting
         */
        audienceNotes?: string | null;
        isActive?: boolean | null;
        /**
         * Last promotional post to this group or page
         */
        lastPostedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Connected WhatsApp Business Cloud API account. Order/like/favorite notifications are sent to the business number below.
   */
  whatsappConfig?: {
    /**
     * Recipient for WhatsApp notifications, in E.164 format (e.g. +13098253354).
     */
    businessNumber?: string | null;
    /**
     * WhatsApp Cloud API phone number ID (from Meta).
     */
    phoneNumberId?: string | null;
    /**
     * WABA ID (from Meta).
     */
    wabaId?: string | null;
    /**
     * Secret WhatsApp Cloud API access token. Never exposed to clients.
     */
    accessToken?: string | null;
    /**
     * When enabled, send WhatsApp notifications for orders, likes, and favorites.
     */
    notificationsEnabled?: boolean | null;
  };
  /**
   * Connected Facebook Page and Instagram Business account used to post products to social channels.
   */
  metaConfig?: {
    facebookPageId?: string | null;
    /**
     * Auto-filled from token. IG Business ID (Facebook path) or Instagram user ID (IGAA path).
     */
    instagramBusinessId?: string | null;
    /**
     * Auto-filled when using an Instagram Login token (IGAA…).
     */
    instagramUsername?: string | null;
    /**
     * Facebook Page access token (EAA…). Used for Facebook + Instagram via Page.
     */
    pageAccessToken?: string | null;
    /**
     * Instagram Login access token (IGAA…). Used for Instagram-only posting without a Facebook Page token.
     */
    instagramAccessToken?: string | null;
  };
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zipcode?: string | null;
    country?: string | null;
  };
  /**
   * Quick action to approve and activate this vendor
   */
  approveAction?: string | null;
  /**
   * Vendor approval status. Use 'Approve & Activate' button to approve vendors.
   */
  status?: ('pending' | 'approved' | 'suspended' | 'rejected') | null;
  /**
   * Active vendors can sell products. Use 'Approve & Activate' button above to activate vendors.
   */
  isActive?: boolean | null;
  /**
   * Stripe Connect account ID for payouts
   */
  stripeAccountId?: string | null;
  /**
   * Stripe Connect account status
   */
  stripeAccountStatus?: ('not_connected' | 'pending' | 'active' | 'restricted' | 'rejected') | null;
  /**
   * Link for vendor to complete Stripe onboarding
   */
  stripeOnboardingLink?: string | null;
  /**
   * Whether vendor has completed Stripe onboarding
   */
  stripeOnboardingCompleted?: boolean | null;
  /**
   * Detailed Stripe account information (business details, capabilities, requirements)
   */
  stripeAccountDetails?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Stripe account country
   */
  stripeAccountCountry?: string | null;
  /**
   * Stripe account email
   */
  stripeAccountEmail?: string | null;
  /**
   * Whether vendor can accept charges
   */
  stripeChargesEnabled?: boolean | null;
  /**
   * Whether vendor can receive payouts
   */
  stripePayoutsEnabled?: boolean | null;
  /**
   * Sync vendor Stripe account details from Stripe API
   */
  syncStripeAction?: string | null;
  /**
   * Platform commission rate (%)
   */
  commissionRate?: number | null;
  /**
   * Phone number for customers to contact you for offline payments
   */
  contactPhone?: string | null;
  /**
   * Email address for customers to contact you for offline payments
   */
  contactEmail?: string | null;
  /**
   * Which payment methods do you want to offer to customers?
   */
  preferredPaymentMethod?: ('stripe' | 'offline' | 'both') | null;
  /**
   * Custom instructions for customers who choose offline payment (e.g., 'Call me at [phone] or WhatsApp me at [number]')
   */
  offlinePaymentInstructions?: string | null;
  /**
   * Business verification documents (business license, tax ID, etc.)
   */
  verificationDocuments?:
    | {
        document: string | Media;
        type: 'business-license' | 'tax-id' | 'identity' | 'other';
        /**
         * Additional notes about this document
         */
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Selected UI/UX template for vendor storefront
   */
  selectedTemplate?: (string | null) | VendorTemplate;
  /**
   * Optional storefront layout override. When empty, the layout from the selected theme is used.
   */
  selectedLayoutId?: ('default' | 'collection' | 'emporium' | 'runway' | 'reloop') | null;
  /**
   * Vendor-specific template customizations (colors, fonts, layout, etc.)
   */
  templateCustomization?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Colorful South Asian monogram designs — vendors pick one initial letter
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-logo-templates".
 */
export interface VendorLogoTemplate {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  previewImage?: (string | null) | Media;
  preset:
    | 'lotus-grace'
    | 'peacock-royal'
    | 'mandala-gold'
    | 'silk-emblem'
    | 'temple-arch'
    | 'rangoli-star'
    | 'diya-lamp'
    | 'jasmine-wreath'
    | 'paisley-curve'
    | 'kite-sankranti'
    | 'henna-scroll'
    | 'marigold-ring'
    | 'chakra-wheel'
    | 'hex-kolam'
    | 'elephant-emblem';
  vendorWords?: {
    word1?: {
      label?: string | null;
      hint?: string | null;
      defaultValue?: string | null;
    };
    word2?: {
      label?: string | null;
      hint?: string | null;
      defaultValue?: string | null;
    };
  };
  defaultWord1?: string | null;
  defaultWord2?: string | null;
  theme?: {
    primary?: string | null;
    secondary?: string | null;
    accent?: string | null;
    tertiary?: string | null;
    highlight?: string | null;
    background?: string | null;
  };
  isDefault?: boolean | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Promotional banner designs vendors can choose from
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "happy-banners".
 */
export interface HappyBanner {
  id: string;
  /**
   * Banner name shown to vendors (e.g. Mega Sale Blue)
   */
  name: string;
  /**
   * URL-safe identifier
   */
  slug: string;
  /**
   * Short description for the vendor picker
   */
  description?: string | null;
  /**
   * Optional thumbnail shown in the vendor banner picker. Recommended ~1200×400px.
   */
  previewImage?: (string | null) | Media;
  preset:
    | 'mega-sale'
    | 'summer-sale'
    | 'hue-editorial'
    | 'tropical-hot-sale'
    | 'new-arrivals'
    | 'ethnic-festive'
    | 'flash-sale'
    | 'bridal-edit'
    | 'linen-edit'
    | 'kurta-print'
    | 'luxury-boutique'
    | 'boho-chic'
    | 'clearance-eoss'
    | 'handloom-heritage';
  /**
   * Same two-word slot pattern for every banner design. Each vendor sets their own values after selecting this design.
   */
  vendorWords?: {
    word1?: {
      label?: string | null;
      hint?: string | null;
      defaultValue?: string | null;
    };
    word2?: {
      label?: string | null;
      hint?: string | null;
      defaultValue?: string | null;
    };
  };
  defaultWord1?: string | null;
  defaultWord2?: string | null;
  eyebrowText?: string | null;
  secondaryWord?: string | null;
  ctaLabel?: string | null;
  discountPrefix?: string | null;
  discountSuffix?: string | null;
  theme?: {
    backgroundColor?: string | null;
    accentYellow?: string | null;
    accentPink?: string | null;
  };
  isDefault?: boolean | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * You must verify your account before creating products
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Price in USD
   */
  price: number;
  /**
   * The vendor/shop that owns this product
   */
  vendor: string | Vendor;
  image?: (string | null) | Media;
  cover?: (string | Media)[] | null;
  /**
   * Choose how to add product video: upload a file or use a YouTube link
   */
  videoSource?: ('upload' | 'youtube') | null;
  /**
   * Product video (MP4, WebM, etc.) - vendors can upload product demonstration videos
   */
  video?: (string | null) | Media;
  /**
   * Paste the full YouTube URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID or https://youtu.be/VIDEO_ID)
   */
  youtubeUrl?: string | null;
  /**
   * Automatically extracted from YouTube URL
   */
  youtubeVideoId?: string | null;
  /**
   * Enter the time where product details are discussed in MM:SS format (e.g., 2:05 for 2 minutes 5 seconds, or 0:30 for 30 seconds)
   */
  youtubeStartTime?: string | null;
  /**
   * Automatically calculated from MM:SS format
   */
  youtubeStartTimeSeconds?: number | null;
  refundPolicy?: ('30-day' | '14-day' | '7-day' | '3-day' | '1-day' | 'no-refunds') | null;
  /**
   * Protected content only visible to customers after purchase. Add product documentation, downloadable files, getting started guides, and bonus materials. Supports Markdown formatting
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * If checked, this product will not be shown on the public storefront
   */
  isPrivate?: boolean | null;
  /**
   * If checked, this product will be archived
   */
  isArchived?: boolean | null;
  /**
   * Select tags for this product
   */
  tags?: (string | Tag)[] | null;
  /**
   * ⚠️ Use the Vendor Dashboard (/vendor/products) to create products with variants. This field is for advanced users only.
   */
  variants?:
    | {
        /**
         * Variant attributes (e.g., { size: 'M', color: 'Red', material: 'Silk' })
         */
        variantData:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * Available inventory for this variant
         */
        stock: number;
        /**
         * Price for this specific variant. If not set, uses the product's base price.
         */
        price?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name: string;
  products?: (string | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * UI/UX templates for vendor storefronts
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-templates".
 */
export interface VendorTemplate {
  id: string;
  /**
   * Template name (e.g., 'Modern Minimal', 'Classic Elegance')
   */
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name)
   */
  slug: string;
  /**
   * Template description shown to vendors
   */
  description?: string | null;
  /**
   * Screenshot/preview image of the template (recommended: 1920x1080px)
   */
  previewImage?: (string | null) | Media;
  /**
   * Small thumbnail for template selection UI (recommended: 400x300px)
   */
  thumbnailImage?: (string | null) | Media;
  /**
   * Template category for filtering
   */
  category: 'minimal' | 'elegant' | 'bold' | 'colorful' | 'classic';
  /**
   * Site-wide default template for new vendors. Only one template can be default; checking this unchecks any other default.
   */
  isDefault?: boolean | null;
  /**
   * Whether template is available for selection
   */
  isActive?: boolean | null;
  /**
   * Template version number
   */
  version?: string | null;
  /**
   * Template creator/author
   */
  author?: string | null;
  /**
   * Template configuration schema (colors, fonts, spacing, layout, components)
   */
  templateConfig:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * CSS custom properties/variables for the template
   */
  cssVariables:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Component structure mapping (which component variants to use)
   */
  componentMapping:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-banners".
 */
export interface HeroBanner {
  id: string;
  /**
   * Title for the hero banner section
   */
  title: string;
  /**
   * Optional subtitle text
   */
  subtitle?: string | null;
  /**
   * Optional background image for the banner
   */
  backgroundImage?: (string | null) | Media;
  /**
   * Select products to display in this hero banner
   */
  products: (string | Product)[];
  /**
   * Only active banners will be displayed on the homepage
   */
  isActive?: boolean | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  /**
   * Unique order number (auto-generated)
   */
  orderNumber: string;
  name: string;
  /**
   * Logged-in customer. Omitted for guest checkout orders.
   */
  user?: (string | null) | User;
  /**
   * Email for guest checkout orders (when user is not set)
   */
  guestEmail?: string | null;
  /**
   * Vendor that should fulfill this order (auto-assigned from product)
   */
  vendor: string | Vendor;
  product: string | Product;
  /**
   * Order status workflow: Pending → Payment Done → Processing → Complete
   */
  status: 'pending' | 'payment_done' | 'processing' | 'complete' | 'canceled' | 'refunded';
  /**
   * Whether product stock was deducted on place or restored on cancel/refund
   */
  inventoryAdjusted?: ('none' | 'deducted' | 'restored') | null;
  /**
   * History of status changes
   */
  statusHistory?:
    | {
        status?: ('pending' | 'payment_done' | 'processing' | 'complete' | 'canceled' | 'refunded') | null;
        timestamp?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Total order amount in USD (customer paid amount)
   */
  total: number;
  /**
   * Platform commission amount (calculated from vendor commissionRate)
   */
  commission?: number | null;
  /**
   * Commission rate (%) used for this order (snapshot from vendor at time of order)
   */
  commissionRate?: number | null;
  /**
   * Quantity of items ordered
   */
  quantity: number;
  /**
   * Product size variant (if applicable)
   */
  size?: string | null;
  /**
   * Product color variant (if applicable)
   */
  color?: string | null;
  /**
   * Stripe checkout session associated with the order (only for Stripe payments)
   */
  stripeCheckoutSessionId?: string | null;
  /**
   * Stripe account associated with the order
   */
  stripeAccountId?: string | null;
  /**
   * Stripe payment intent ID
   */
  stripePaymentIntentId?: string | null;
  /**
   * Stripe transfer ID (for vendor payout via Stripe Connect)
   */
  stripeTransferId?: string | null;
  /**
   * Status of the transfer to vendor's Stripe account
   */
  transferStatus?: ('pending' | 'paid' | 'failed' | 'canceled') | null;
  /**
   * How the customer chose to pay for this order
   */
  paymentMethod: 'stripe' | 'offline';
  /**
   * Current payment status for this order
   */
  paymentStatus: 'pending' | 'completed' | 'failed' | 'refunded';
  /**
   * Contact information for offline payment (vendor and customer)
   */
  offlinePaymentContact?: {
    phone?: string | null;
    email?: string | null;
    /**
     * Customer's phone number for vendor to contact them
     */
    customerPhone?: string | null;
  };
  /**
   * Any notes about the offline payment arrangement
   */
  offlinePaymentNotes?: string | null;
  /**
   * Shipping address for this order (snapshot at time of order)
   */
  shippingAddress: {
    /**
     * Full name of the recipient
     */
    fullName: string;
    /**
     * Contact phone number for delivery
     */
    phone?: string | null;
    /**
     * Street address, apartment, suite, etc.
     */
    street: string;
    city: string;
    state:
      | 'AL'
      | 'AK'
      | 'AZ'
      | 'AR'
      | 'CA'
      | 'CO'
      | 'CT'
      | 'DE'
      | 'FL'
      | 'GA'
      | 'HI'
      | 'ID'
      | 'IL'
      | 'IN'
      | 'IA'
      | 'KS'
      | 'KY'
      | 'LA'
      | 'ME'
      | 'MD'
      | 'MA'
      | 'MI'
      | 'MN'
      | 'MS'
      | 'MO'
      | 'MT'
      | 'NE'
      | 'NV'
      | 'NH'
      | 'NJ'
      | 'NM'
      | 'NY'
      | 'NC'
      | 'ND'
      | 'OH'
      | 'OK'
      | 'OR'
      | 'PA'
      | 'RI'
      | 'SC'
      | 'SD'
      | 'TN'
      | 'TX'
      | 'UT'
      | 'VT'
      | 'VA'
      | 'WA'
      | 'WV'
      | 'WI'
      | 'WY'
      | 'DC';
    /**
     * 5-digit ZIP code or ZIP+4 format (e.g., 12345 or 12345-6789)
     */
    zipcode: string;
    /**
     * Country for shipping
     */
    country?: string | null;
  };
  /**
   * Shipping method selected for this order
   */
  shippingMethod?: ('standard' | 'express' | 'overnight' | 'international' | 'local' | 'pickup') | null;
  /**
   * Shipping cost in USD
   */
  shippingCost?: number | null;
  /**
   * Current shipping status
   */
  shippingStatus?:
    | (
        | 'pending'
        | 'label_created'
        | 'shipped'
        | 'in_transit'
        | 'out_for_delivery'
        | 'delivered'
        | 'exception'
        | 'returned'
      )
    | null;
  /**
   * Shipping tracking number
   */
  trackingNumber?: string | null;
  /**
   * Shipping carrier
   */
  carrier?: ('usps' | 'fedex' | 'ups' | 'dhl' | 'other') | null;
  /**
   * Tracking URL (auto-generated if carrier is selected)
   */
  trackingUrl?: string | null;
  /**
   * Estimated delivery date
   */
  estimatedDelivery?: string | null;
  /**
   * Actual delivery date (when package was delivered)
   */
  actualDeliveryDate?: string | null;
  /**
   * URL to shipping label PDF
   */
  shippingLabelUrl?: string | null;
  /**
   * Package weight in pounds (lbs)
   */
  packageWeight?: number | null;
  /**
   * Package dimensions for shipping calculations
   */
  packageDimensions?: {
    length?: number | null;
    width?: number | null;
    height?: number | null;
  };
  /**
   * Insurance value for the shipment in USD
   */
  insuranceValue?: number | null;
  /**
   * Payout details for the vendor
   */
  vendorPayout?: {
    /**
     * Amount to be paid to vendor (after commission)
     */
    amount?: number | null;
    /**
     * Platform commission amount
     */
    commissionAmount?: number | null;
    /**
     * Payout status
     */
    status?: ('pending' | 'processing' | 'completed' | 'failed') | null;
    /**
     * Date when payout was processed
     */
    payoutDate?: string | null;
    /**
     * Stripe transfer/payout transaction ID
     */
    transactionId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Application and vendor-level roles for user permissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: string;
  /**
   * Role name (e.g., 'Vendor Owner', 'App Admin')
   */
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name)
   */
  slug: string;
  /**
   * Role type: Application roles are for app-level access, Vendor roles are for vendor organization access
   */
  type: 'app' | 'vendor';
  /**
   * Description of what this role allows
   */
  description?: string | null;
  /**
   * List of permissions granted by this role
   */
  permissions?:
    | {
        /**
         * Permission name (e.g., 'manage-products', 'view-orders')
         */
        permission: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Active roles can be assigned to users
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  /**
   * The user account associated with this customer
   */
  user: string | User;
  /**
   * Customer name (synced from user)
   */
  name: string;
  /**
   * Customer email (synced from user)
   */
  email: string;
  /**
   * Customer phone number (optional)
   */
  phone?: string | null;
  /**
   * Vendors this customer has ordered from
   */
  vendors?: (string | Vendor)[] | null;
  /**
   * Total number of orders across all vendors
   */
  totalOrders?: number | null;
  /**
   * Total amount spent across all vendors
   */
  totalSpent?: number | null;
  /**
   * Date of most recent order
   */
  lastOrderDate?: string | null;
  /**
   * Date of first order
   */
  firstOrderDate?: string | null;
  /**
   * Customer tags/segments (can be vendor-specific or global)
   */
  tags?:
    | {
        tag: string;
        /**
         * Vendor who added this tag (null for global tags)
         */
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  /**
   * Customer notes (vendor-specific)
   */
  notes?:
    | {
        text: string;
        /**
         * Vendor who added this note
         */
        vendor?: (string | null) | Vendor;
        /**
         * User who created this note
         */
        createdBy?: (string | null) | User;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Define variant types (e.g., Size, Color, Material). These are assigned to categories.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variant-types".
 */
export interface VariantType {
  id: string;
  name: string;
  slug: string;
  type: 'select' | 'number' | 'text';
  /**
   * Unit for number type (e.g., 'inches', 'meters')
   */
  unit?: string | null;
  /**
   * Order in which this variant type should be displayed
   */
  displayOrder: number;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage variant option values (e.g., 'Small', 'Red', 'Silk'). These appear in product variant dropdowns.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variant-options".
 */
export interface VariantOption {
  id: string;
  value: string;
  /**
   * Display label (if different from value)
   */
  label?: string | null;
  /**
   * The variant type this option belongs to
   */
  variantType: string | VariantType;
  /**
   * Hex color code (for color variant options)
   */
  hexCode?: string | null;
  /**
   * Image for this option (e.g., color swatch)
   */
  image?: (string | null) | Media;
  /**
   * Order in which this option should be displayed
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-hero-banners".
 */
export interface VendorHeroBanner {
  id: string;
  /**
   * The vendor who owns this banner
   */
  vendor: string | Vendor;
  /**
   * Title for the hero banner section
   */
  title: string;
  /**
   * Optional subtitle text
   */
  subtitle?: string | null;
  /**
   * Optional background image for the banner (recommended: 1920x500px)
   */
  backgroundImage?: (string | null) | Media;
  /**
   * Select products to display in this hero banner (only your own products)
   */
  products: (string | Product)[];
  /**
   * Only active banners will be displayed on your vendor page
   */
  isActive?: boolean | null;
  /**
   * Display order (lower numbers appear first). Leave empty for default ordering.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Regions and prospect vendor names for outreach (staff only).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "potential-vendor-regions".
 */
export interface PotentialVendorRegion {
  id: string;
  /**
   * e.g. "Charlotte", "Raleigh", "Triad"
   */
  region: string;
  /**
   * Prospect business or vendor names in this region
   */
  potentialVendors?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers appear first in the staff list
   */
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Products a customer has favorited.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites".
 */
export interface Favorite {
  id: string;
  user: string | User;
  product: string | Product;
  updatedAt: string;
  createdAt: string;
}
/**
 * Likes a customer has given to products.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-likes".
 */
export interface ProductLike {
  id: string;
  user: string | User;
  product: string | Product;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer comments on products.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-comments".
 */
export interface ProductComment {
  id: string;
  user: string | User;
  product: string | Product;
  comment: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Log of products posted to Instagram, Facebook, and WhatsApp.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-posts".
 */
export interface SocialPost {
  id: string;
  vendor: string | Vendor;
  product: string | Product;
  channels: ('instagram' | 'facebook' | 'whatsapp')[];
  caption?: string | null;
  status: 'draft' | 'posted' | 'failed';
  /**
   * ID returned by the social platform for the created post.
   */
  externalPostId?: string | null;
  /**
   * Error message if the post failed.
   */
  error?: string | null;
  postedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'hero-banners';
        value: string | HeroBanner;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'vendors';
        value: string | Vendor;
      } | null)
    | ({
        relationTo: 'roles';
        value: string | Role;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'variant-types';
        value: string | VariantType;
      } | null)
    | ({
        relationTo: 'variant-options';
        value: string | VariantOption;
      } | null)
    | ({
        relationTo: 'vendor-hero-banners';
        value: string | VendorHeroBanner;
      } | null)
    | ({
        relationTo: 'vendor-templates';
        value: string | VendorTemplate;
      } | null)
    | ({
        relationTo: 'happy-banners';
        value: string | HappyBanner;
      } | null)
    | ({
        relationTo: 'vendor-logo-templates';
        value: string | VendorLogoTemplate;
      } | null)
    | ({
        relationTo: 'potential-vendor-regions';
        value: string | PotentialVendorRegion;
      } | null)
    | ({
        relationTo: 'favorites';
        value: string | Favorite;
      } | null)
    | ({
        relationTo: 'product-likes';
        value: string | ProductLike;
      } | null)
    | ({
        relationTo: 'product-comments';
        value: string | ProductComment;
      } | null)
    | ({
        relationTo: 'social-posts';
        value: string | SocialPost;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  name?: T;
  role?: T;
  oauthProvider?: T;
  oauthId?: T;
  avatar?: T;
  vendor?: T;
  shippingAddresses?:
    | T
    | {
        label?: T;
        isDefault?: T;
        fullName?: T;
        phone?: T;
        street?: T;
        city?: T;
        state?: T;
        zipcode?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  price?: T;
  vendor?: T;
  image?: T;
  cover?: T;
  videoSource?: T;
  video?: T;
  youtubeUrl?: T;
  youtubeVideoId?: T;
  youtubeStartTime?: T;
  youtubeStartTimeSeconds?: T;
  refundPolicy?: T;
  content?: T;
  isPrivate?: T;
  isArchived?: T;
  tags?: T;
  variants?:
    | T
    | {
        variantData?: T;
        stock?: T;
        price?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-banners_select".
 */
export interface HeroBannersSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  backgroundImage?: T;
  products?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  name?: T;
  user?: T;
  guestEmail?: T;
  vendor?: T;
  product?: T;
  status?: T;
  inventoryAdjusted?: T;
  statusHistory?:
    | T
    | {
        status?: T;
        timestamp?: T;
        note?: T;
        id?: T;
      };
  total?: T;
  commission?: T;
  commissionRate?: T;
  quantity?: T;
  size?: T;
  color?: T;
  stripeCheckoutSessionId?: T;
  stripeAccountId?: T;
  stripePaymentIntentId?: T;
  stripeTransferId?: T;
  transferStatus?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  offlinePaymentContact?:
    | T
    | {
        phone?: T;
        email?: T;
        customerPhone?: T;
      };
  offlinePaymentNotes?: T;
  shippingAddress?:
    | T
    | {
        fullName?: T;
        phone?: T;
        street?: T;
        city?: T;
        state?: T;
        zipcode?: T;
        country?: T;
      };
  shippingMethod?: T;
  shippingCost?: T;
  shippingStatus?: T;
  trackingNumber?: T;
  carrier?: T;
  trackingUrl?: T;
  estimatedDelivery?: T;
  actualDeliveryDate?: T;
  shippingLabelUrl?: T;
  packageWeight?: T;
  packageDimensions?:
    | T
    | {
        length?: T;
        width?: T;
        height?: T;
      };
  insuranceValue?: T;
  vendorPayout?:
    | T
    | {
        amount?: T;
        commissionAmount?: T;
        status?: T;
        payoutDate?: T;
        transactionId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors_select".
 */
export interface VendorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  logo?: T;
  logoSource?: T;
  logoTemplate?:
    | T
    | {
        selectedTemplate?: T;
        word1?: T;
        word2?: T;
      };
  coverImage?: T;
  happyBanner?:
    | T
    | {
        selectedBanner?: T;
        word1?: T;
        word2?: T;
      };
  heroBanner?:
    | T
    | {
        title?: T;
        subtitle?: T;
        backgroundImage?: T;
        products?: T;
        isActive?: T;
        order?: T;
      };
  email?: T;
  phone?: T;
  website?: T;
  socialChannels?:
    | T
    | {
        socialInstagram?: T;
        socialInstagramLastPostedAt?: T;
        socialFacebook?: T;
        socialFacebookLastPostedAt?: T;
        socialWhatsAppGroup?: T;
        socialWhatsAppGroupLastPostedAt?: T;
        socialNotes?: T;
      };
  marketingChannels?:
    | T
    | {
        platform?: T;
        name?: T;
        url?: T;
        region?: T;
        audienceNotes?: T;
        isActive?: T;
        lastPostedAt?: T;
        id?: T;
      };
  whatsappConfig?:
    | T
    | {
        businessNumber?: T;
        phoneNumberId?: T;
        wabaId?: T;
        accessToken?: T;
        notificationsEnabled?: T;
      };
  metaConfig?:
    | T
    | {
        facebookPageId?: T;
        instagramBusinessId?: T;
        instagramUsername?: T;
        pageAccessToken?: T;
        instagramAccessToken?: T;
      };
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zipcode?: T;
        country?: T;
      };
  approveAction?: T;
  status?: T;
  isActive?: T;
  stripeAccountId?: T;
  stripeAccountStatus?: T;
  stripeOnboardingLink?: T;
  stripeOnboardingCompleted?: T;
  stripeAccountDetails?: T;
  stripeAccountCountry?: T;
  stripeAccountEmail?: T;
  stripeChargesEnabled?: T;
  stripePayoutsEnabled?: T;
  syncStripeAction?: T;
  commissionRate?: T;
  contactPhone?: T;
  contactEmail?: T;
  preferredPaymentMethod?: T;
  offlinePaymentInstructions?: T;
  verificationDocuments?:
    | T
    | {
        document?: T;
        type?: T;
        notes?: T;
        id?: T;
      };
  selectedTemplate?: T;
  selectedLayoutId?: T;
  templateCustomization?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  description?: T;
  permissions?:
    | T
    | {
        permission?: T;
        id?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  email?: T;
  phone?: T;
  vendors?: T;
  totalOrders?: T;
  totalSpent?: T;
  lastOrderDate?: T;
  firstOrderDate?: T;
  tags?:
    | T
    | {
        tag?: T;
        vendor?: T;
        id?: T;
      };
  notes?:
    | T
    | {
        text?: T;
        vendor?: T;
        createdBy?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variant-types_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  unit?: T;
  displayOrder?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variant-options_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  value?: T;
  label?: T;
  variantType?: T;
  hexCode?: T;
  image?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-hero-banners_select".
 */
export interface VendorHeroBannersSelect<T extends boolean = true> {
  vendor?: T;
  title?: T;
  subtitle?: T;
  backgroundImage?: T;
  products?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-templates_select".
 */
export interface VendorTemplatesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  previewImage?: T;
  thumbnailImage?: T;
  category?: T;
  isDefault?: T;
  isActive?: T;
  version?: T;
  author?: T;
  templateConfig?: T;
  cssVariables?: T;
  componentMapping?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "happy-banners_select".
 */
export interface HappyBannersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  previewImage?: T;
  preset?: T;
  vendorWords?:
    | T
    | {
        word1?:
          | T
          | {
              label?: T;
              hint?: T;
              defaultValue?: T;
            };
        word2?:
          | T
          | {
              label?: T;
              hint?: T;
              defaultValue?: T;
            };
      };
  defaultWord1?: T;
  defaultWord2?: T;
  eyebrowText?: T;
  secondaryWord?: T;
  ctaLabel?: T;
  discountPrefix?: T;
  discountSuffix?: T;
  theme?:
    | T
    | {
        backgroundColor?: T;
        accentYellow?: T;
        accentPink?: T;
      };
  isDefault?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-logo-templates_select".
 */
export interface VendorLogoTemplatesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  previewImage?: T;
  preset?: T;
  vendorWords?:
    | T
    | {
        word1?:
          | T
          | {
              label?: T;
              hint?: T;
              defaultValue?: T;
            };
        word2?:
          | T
          | {
              label?: T;
              hint?: T;
              defaultValue?: T;
            };
      };
  defaultWord1?: T;
  defaultWord2?: T;
  theme?:
    | T
    | {
        primary?: T;
        secondary?: T;
        accent?: T;
        tertiary?: T;
        highlight?: T;
        background?: T;
      };
  isDefault?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "potential-vendor-regions_select".
 */
export interface PotentialVendorRegionsSelect<T extends boolean = true> {
  region?: T;
  potentialVendors?:
    | T
    | {
        name?: T;
        id?: T;
      };
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites_select".
 */
export interface FavoritesSelect<T extends boolean = true> {
  user?: T;
  product?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-likes_select".
 */
export interface ProductLikesSelect<T extends boolean = true> {
  user?: T;
  product?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-comments_select".
 */
export interface ProductCommentsSelect<T extends boolean = true> {
  user?: T;
  product?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-posts_select".
 */
export interface SocialPostsSelect<T extends boolean = true> {
  vendor?: T;
  product?: T;
  channels?: T;
  caption?: T;
  status?: T;
  externalPostId?: T;
  error?: T;
  postedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Master switch for Happy Banners on vendor storefronts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-banner-config".
 */
export interface HeroBannerConfig {
  id: string;
  enabled?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-banner-config_select".
 */
export interface HeroBannerConfigSelect<T extends boolean = true> {
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}