/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    tags: Tag;
    'hero-banners': HeroBanner;
    orders: Order;
    vendors: Vendor;
    roles: Role;
    customers: Customer;
    'variant-types': VariantType;
    'variant-options': VariantOption;
    'vendor-tasks': VendorTask;
    'vendor-task-messages': VendorTaskMessage;
    'vendor-hero-banners': VendorHeroBanner;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      subcategories: 'categories';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'hero-banners': HeroBannersSelect<false> | HeroBannersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    vendors: VendorsSelect<false> | VendorsSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'variant-types': VariantTypesSelect<false> | VariantTypesSelect<true>;
    'variant-options': VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    'vendor-tasks': VendorTasksSelect<false> | VendorTasksSelect<true>;
    'vendor-task-messages': VendorTaskMessagesSelect<false> | VendorTaskMessagesSelect<true>;
    'vendor-hero-banners': VendorHeroBannersSelect<false> | VendorHeroBannersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  username?: string | null;
  name?: string | null;
  /**
   * ⚠️ DEPRECATED: Use appRole and vendorRole instead. Kept for backward compatibility.
   */
  roles?: ('super-admin' | 'user')[] | null;
  /**
   * The vendor/shop this user belongs to. Required for all users except App Admins.
   */
  vendor?: (string | null) | Vendor;
  /**
   * Role within the vendor organization (e.g., Vendor Owner, Vendor Manager, Vendor Staff)
   */
  vendorRole?: (string | null) | Role;
  /**
   * Application-level role (e.g., App Admin, App Support, Customer). App Admin does not require a vendor.
   */
  appRole?: (string | null) | Role;
  oauthProviders?: {
    google?: {
      id?: string | null;
      email?: string | null;
    };
    facebook?: {
      id?: string | null;
      email?: string | null;
    };
  };
  profilePicture?: string | null;
  /**
   * Manage multiple shipping addresses. Set one as default for faster checkout.
   */
  shippingAddresses?:
    | {
        /**
         * e.g., Home, Work, Office
         */
        label: string;
        /**
         * Set as default shipping address
         */
        isDefault?: boolean | null;
        /**
         * Recipient's full name
         */
        fullName: string;
        /**
         * Contact phone number (e.g., +1-555-123-4567)
         */
        phone: string;
        /**
         * Street address, apartment, suite, etc.
         */
        street: string;
        city: string;
        state:
          | 'AL'
          | 'AK'
          | 'AZ'
          | 'AR'
          | 'CA'
          | 'CO'
          | 'CT'
          | 'DE'
          | 'FL'
          | 'GA'
          | 'HI'
          | 'ID'
          | 'IL'
          | 'IN'
          | 'IA'
          | 'KS'
          | 'KY'
          | 'LA'
          | 'ME'
          | 'MD'
          | 'MA'
          | 'MI'
          | 'MN'
          | 'MS'
          | 'MO'
          | 'MT'
          | 'NE'
          | 'NV'
          | 'NH'
          | 'NJ'
          | 'NM'
          | 'NY'
          | 'NC'
          | 'ND'
          | 'OH'
          | 'OK'
          | 'OR'
          | 'PA'
          | 'RI'
          | 'SC'
          | 'SD'
          | 'TN'
          | 'TX'
          | 'UT'
          | 'VT'
          | 'VA'
          | 'WA'
          | 'WV'
          | 'WI'
          | 'WY'
          | 'DC';
        /**
         * 5-digit ZIP code or ZIP+4 format (e.g., 12345 or 12345-6789)
         */
        zipcode: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Vendors/Sellers in the marketplace
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors".
 */
export interface Vendor {
  id: string;
  /**
   * Business/Vendor name
   */
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name)
   */
  slug: string;
  /**
   * Vendor description/bio
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Vendor logo image
   */
  logo?: (string | null) | Media;
  /**
   * Vendor cover/banner image (fallback if hero banner not configured)
   */
  coverImage?: (string | null) | Media;
  /**
   * Configure a custom hero banner for your vendor page. If not configured, the cover image will be used.
   */
  heroBanner?: {
    /**
     * Main title displayed on the hero banner (e.g., 'Welcome to [Vendor Name]')
     */
    title?: string | null;
    /**
     * Optional subtitle text displayed below the title
     */
    subtitle?: string | null;
    /**
     * Background image for the hero banner (recommended: 1920x500px). If not set, a gradient will be used.
     */
    backgroundImage?: (string | null) | Media;
    /**
     * Select products to display in the hero banner (4-6 products recommended). Only your own products can be selected.
     */
    products?: (string | Product)[] | null;
    /**
     * Only active hero banners will be displayed on your vendor page
     */
    isActive?: boolean | null;
    /**
     * Display order (lower numbers appear first, if multiple banners exist)
     */
    order?: number | null;
  };
  /**
   * Business email address
   */
  email: string;
  /**
   * Business phone number
   */
  phone?: string | null;
  /**
   * Business website URL
   */
  website?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zipcode?: string | null;
    country?: string | null;
  };
  /**
   * Quick action to approve and activate this vendor
   */
  approveAction?: string | null;
  /**
   * Vendor approval status. Use 'Approve & Activate' button to approve vendors.
   */
  status?: ('pending' | 'approved' | 'suspended' | 'rejected') | null;
  /**
   * Active vendors can sell products. Use 'Approve & Activate' button above to activate vendors.
   */
  isActive?: boolean | null;
  /**
   * Stripe Connect account ID for payouts
   */
  stripeAccountId?: string | null;
  /**
   * Stripe Connect account status
   */
  stripeAccountStatus?: ('not_connected' | 'pending' | 'active' | 'restricted' | 'rejected') | null;
  /**
   * Link for vendor to complete Stripe onboarding
   */
  stripeOnboardingLink?: string | null;
  /**
   * Whether vendor has completed Stripe onboarding
   */
  stripeOnboardingCompleted?: boolean | null;
  /**
   * Detailed Stripe account information (business details, capabilities, requirements)
   */
  stripeAccountDetails?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Stripe account country
   */
  stripeAccountCountry?: string | null;
  /**
   * Stripe account email
   */
  stripeAccountEmail?: string | null;
  /**
   * Whether vendor can accept charges
   */
  stripeChargesEnabled?: boolean | null;
  /**
   * Whether vendor can receive payouts
   */
  stripePayoutsEnabled?: boolean | null;
  /**
   * Sync vendor Stripe account details from Stripe API
   */
  syncStripeAction?: string | null;
  /**
   * Platform commission rate (%)
   */
  commissionRate?: number | null;
  /**
   * Phone number for customers to contact you for offline payments
   */
  contactPhone?: string | null;
  /**
   * Email address for customers to contact you for offline payments
   */
  contactEmail?: string | null;
  /**
   * Which payment methods do you want to offer to customers?
   */
  preferredPaymentMethod?: ('stripe' | 'offline' | 'both') | null;
  /**
   * Custom instructions for customers who choose offline payment (e.g., 'Call me at [phone] or WhatsApp me at [number]')
   */
  offlinePaymentInstructions?: string | null;
  /**
   * Business verification documents (business license, tax ID, etc.)
   */
  verificationDocuments?:
    | {
        document: string | Media;
        type: 'business-license' | 'tax-id' | 'identity' | 'other';
        /**
         * Additional notes about this document
         */
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * You must verify your account before creating products
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Price in USD
   */
  price: number;
  /**
   * The vendor/shop that owns this product
   */
  vendor: string | Vendor;
  /**
   * Select a category for this product
   */
  category: string | Category;
  /**
   * Select a subcategory for this product (optional)
   */
  subcategory?: (string | null) | Category;
  image?: (string | null) | Media;
  cover?: (string | null) | Media;
  /**
   * Choose how to add product video: upload a file or use a YouTube link
   */
  videoSource?: ('upload' | 'youtube') | null;
  /**
   * Product video (MP4, WebM, etc.) - vendors can upload product demonstration videos
   */
  video?: (string | null) | Media;
  /**
   * Paste the full YouTube URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID or https://youtu.be/VIDEO_ID)
   */
  youtubeUrl?: string | null;
  /**
   * Automatically extracted from YouTube URL
   */
  youtubeVideoId?: string | null;
  /**
   * Enter the time where product details are discussed in MM:SS format (e.g., 2:05 for 2 minutes 5 seconds, or 0:30 for 30 seconds)
   */
  youtubeStartTime?: string | null;
  /**
   * Automatically calculated from MM:SS format
   */
  youtubeStartTimeSeconds?: number | null;
  refundPolicy?: ('30-day' | '14-day' | '7-day' | '3-day' | '1-day' | 'no-refunds') | null;
  /**
   * Protected content only visible to customers after purchase. Add product documentation, downloadable files, getting started guides, and bonus materials. Supports Markdown formatting
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * If checked, this product will not be shown on the public storefront
   */
  isPrivate?: boolean | null;
  /**
   * If checked, this product will be archived
   */
  isArchived?: boolean | null;
  /**
   * Select tags for this product
   */
  tags?: (string | Tag)[] | null;
  /**
   * ⚠️ Use the Vendor Dashboard (/vendor/products) to create products with variants. Variant fields are dynamically generated based on the selected category. This field is for advanced users only.
   */
  variants?:
    | {
        /**
         * Dynamic variant data based on category variant types (e.g., { size: 'M', color: 'Red', material: 'Silk' })
         */
        variantData:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * Available inventory for this variant
         */
        stock: number;
        /**
         * Price for this specific variant. If not set, uses the product's base price.
         */
        price?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage product categories and their variant configurations
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug: string;
  color?: string | null;
  parent?: (string | null) | Category;
  subcategories?: {
    docs?: (string | Category)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  variantConfig?: {
    /**
     * Variant types that are required for products in this category
     */
    requiredVariants?: (string | VariantType)[] | null;
    /**
     * Variant types that are optional for products in this category
     */
    optionalVariants?: (string | VariantType)[] | null;
    /**
     * Mapping of variant types to their allowed options (JSON format)
     */
    variantOptions?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    pricingRules?: {
      /**
       * Use base price from product
       */
      basePrice?: boolean | null;
      /**
       * Price overrides by size (e.g., { 'XL': 5, '2XL': 10 })
       */
      sizeOverrides?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
      /**
       * Price overrides by color (e.g., { 'Rose Gold': 20, 'Gold': 10 })
       */
      colorOverrides?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
      /**
       * Price overrides by material (e.g., { 'Silk': 20, 'Silver': 50 })
       */
      materialOverrides?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Define variant types (e.g., Size, Color, Material). These are assigned to categories.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variant-types".
 */
export interface VariantType {
  id: string;
  name: string;
  slug: string;
  type: 'select' | 'number' | 'text';
  /**
   * Unit for number type (e.g., 'inches', 'meters')
   */
  unit?: string | null;
  /**
   * Order in which this variant type should be displayed
   */
  displayOrder: number;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name: string;
  products?: (string | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Application and vendor-level roles for user permissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: string;
  /**
   * Role name (e.g., 'Vendor Owner', 'App Admin')
   */
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name)
   */
  slug: string;
  /**
   * Role type: Application roles are for app-level access, Vendor roles are for vendor organization access
   */
  type: 'app' | 'vendor';
  /**
   * Description of what this role allows
   */
  description?: string | null;
  /**
   * List of permissions granted by this role
   */
  permissions?:
    | {
        /**
         * Permission name (e.g., 'manage-products', 'view-orders')
         */
        permission: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Active roles can be assigned to users
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-banners".
 */
export interface HeroBanner {
  id: string;
  /**
   * Title for the hero banner section
   */
  title: string;
  /**
   * Optional subtitle text
   */
  subtitle?: string | null;
  /**
   * Optional background image for the banner
   */
  backgroundImage?: (string | null) | Media;
  /**
   * Select products to display in this hero banner
   */
  products: (string | Product)[];
  /**
   * Only active banners will be displayed on the homepage
   */
  isActive?: boolean | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  /**
   * Unique order number (auto-generated)
   */
  orderNumber: string;
  name: string;
  user: string | User;
  /**
   * Vendor that should fulfill this order (auto-assigned from product)
   */
  vendor: string | Vendor;
  product: string | Product;
  /**
   * Order status workflow: Pending → Payment Done → Processing → Complete
   */
  status: 'pending' | 'payment_done' | 'processing' | 'complete' | 'canceled' | 'refunded';
  /**
   * History of status changes
   */
  statusHistory?:
    | {
        status?: ('pending' | 'payment_done' | 'processing' | 'complete' | 'canceled' | 'refunded') | null;
        timestamp?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Total order amount in USD (customer paid amount)
   */
  total: number;
  /**
   * Platform commission amount (calculated from vendor commissionRate)
   */
  commission?: number | null;
  /**
   * Commission rate (%) used for this order (snapshot from vendor at time of order)
   */
  commissionRate?: number | null;
  /**
   * Quantity of items ordered
   */
  quantity: number;
  /**
   * Product size variant (if applicable)
   */
  size?: string | null;
  /**
   * Product color variant (if applicable)
   */
  color?: string | null;
  /**
   * Stripe checkout session associated with the order (only for Stripe payments)
   */
  stripeCheckoutSessionId?: string | null;
  /**
   * Stripe account associated with the order
   */
  stripeAccountId?: string | null;
  /**
   * Stripe payment intent ID
   */
  stripePaymentIntentId?: string | null;
  /**
   * Stripe transfer ID (for vendor payout via Stripe Connect)
   */
  stripeTransferId?: string | null;
  /**
   * Status of the transfer to vendor's Stripe account
   */
  transferStatus?: ('pending' | 'paid' | 'failed' | 'canceled') | null;
  /**
   * How the customer chose to pay for this order
   */
  paymentMethod: 'stripe' | 'offline';
  /**
   * Current payment status for this order
   */
  paymentStatus: 'pending' | 'completed' | 'failed' | 'refunded';
  /**
   * Contact information for offline payment (vendor and customer)
   */
  offlinePaymentContact?: {
    phone?: string | null;
    email?: string | null;
    /**
     * Customer's phone number for vendor to contact them
     */
    customerPhone?: string | null;
  };
  /**
   * Any notes about the offline payment arrangement
   */
  offlinePaymentNotes?: string | null;
  /**
   * Shipping address for this order (snapshot at time of order)
   */
  shippingAddress: {
    /**
     * Full name of the recipient
     */
    fullName: string;
    /**
     * Contact phone number for delivery
     */
    phone?: string | null;
    /**
     * Street address, apartment, suite, etc.
     */
    street: string;
    city: string;
    state:
      | 'AL'
      | 'AK'
      | 'AZ'
      | 'AR'
      | 'CA'
      | 'CO'
      | 'CT'
      | 'DE'
      | 'FL'
      | 'GA'
      | 'HI'
      | 'ID'
      | 'IL'
      | 'IN'
      | 'IA'
      | 'KS'
      | 'KY'
      | 'LA'
      | 'ME'
      | 'MD'
      | 'MA'
      | 'MI'
      | 'MN'
      | 'MS'
      | 'MO'
      | 'MT'
      | 'NE'
      | 'NV'
      | 'NH'
      | 'NJ'
      | 'NM'
      | 'NY'
      | 'NC'
      | 'ND'
      | 'OH'
      | 'OK'
      | 'OR'
      | 'PA'
      | 'RI'
      | 'SC'
      | 'SD'
      | 'TN'
      | 'TX'
      | 'UT'
      | 'VT'
      | 'VA'
      | 'WA'
      | 'WV'
      | 'WI'
      | 'WY'
      | 'DC';
    /**
     * 5-digit ZIP code or ZIP+4 format (e.g., 12345 or 12345-6789)
     */
    zipcode: string;
    /**
     * Country for shipping
     */
    country?: string | null;
  };
  /**
   * Shipping method selected for this order
   */
  shippingMethod?: ('standard' | 'express' | 'overnight' | 'international' | 'local' | 'pickup') | null;
  /**
   * Shipping cost in USD
   */
  shippingCost?: number | null;
  /**
   * Current shipping status
   */
  shippingStatus?:
    | (
        | 'pending'
        | 'label_created'
        | 'shipped'
        | 'in_transit'
        | 'out_for_delivery'
        | 'delivered'
        | 'exception'
        | 'returned'
      )
    | null;
  /**
   * Shipping tracking number
   */
  trackingNumber?: string | null;
  /**
   * Shipping carrier
   */
  carrier?: ('usps' | 'fedex' | 'ups' | 'dhl' | 'other') | null;
  /**
   * Tracking URL (auto-generated if carrier is selected)
   */
  trackingUrl?: string | null;
  /**
   * Estimated delivery date
   */
  estimatedDelivery?: string | null;
  /**
   * Actual delivery date (when package was delivered)
   */
  actualDeliveryDate?: string | null;
  /**
   * URL to shipping label PDF
   */
  shippingLabelUrl?: string | null;
  /**
   * Package weight in pounds (lbs)
   */
  packageWeight?: number | null;
  /**
   * Package dimensions for shipping calculations
   */
  packageDimensions?: {
    length?: number | null;
    width?: number | null;
    height?: number | null;
  };
  /**
   * Insurance value for the shipment in USD
   */
  insuranceValue?: number | null;
  /**
   * Payout details for the vendor
   */
  vendorPayout?: {
    /**
     * Amount to be paid to vendor (after commission)
     */
    amount?: number | null;
    /**
     * Platform commission amount
     */
    commissionAmount?: number | null;
    /**
     * Payout status
     */
    status?: ('pending' | 'processing' | 'completed' | 'failed') | null;
    /**
     * Date when payout was processed
     */
    payoutDate?: string | null;
    /**
     * Stripe transfer/payout transaction ID
     */
    transactionId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  /**
   * The user account associated with this customer
   */
  user: string | User;
  /**
   * Customer name (synced from user)
   */
  name: string;
  /**
   * Customer email (synced from user)
   */
  email: string;
  /**
   * Customer phone number (optional)
   */
  phone?: string | null;
  /**
   * Vendors this customer has ordered from
   */
  vendors?: (string | Vendor)[] | null;
  /**
   * Total number of orders across all vendors
   */
  totalOrders?: number | null;
  /**
   * Total amount spent across all vendors
   */
  totalSpent?: number | null;
  /**
   * Date of most recent order
   */
  lastOrderDate?: string | null;
  /**
   * Date of first order
   */
  firstOrderDate?: string | null;
  /**
   * Customer tags/segments (can be vendor-specific or global)
   */
  tags?:
    | {
        tag: string;
        /**
         * Vendor who added this tag (null for global tags)
         */
        vendor?: (string | null) | Vendor;
        id?: string | null;
      }[]
    | null;
  /**
   * Customer notes (vendor-specific)
   */
  notes?:
    | {
        text: string;
        /**
         * Vendor who added this note
         */
        vendor?: (string | null) | Vendor;
        /**
         * User who created this note
         */
        createdBy?: (string | null) | User;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage variant option values (e.g., 'Small', 'Red', 'Silk'). These appear in product variant dropdowns.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variant-options".
 */
export interface VariantOption {
  id: string;
  value: string;
  /**
   * Display label (if different from value)
   */
  label?: string | null;
  /**
   * The variant type this option belongs to
   */
  variantType: string | VariantType;
  /**
   * If set, this option is specific to this category. If null, it's global.
   */
  category?: (string | null) | Category;
  /**
   * Hex color code (for color variant options)
   */
  hexCode?: string | null;
  /**
   * Image for this option (e.g., color swatch)
   */
  image?: (string | null) | Media;
  /**
   * Order in which this option should be displayed
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Support tasks and communication between vendors and BDO/admin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-tasks".
 */
export interface VendorTask {
  id: string;
  title: string;
  /**
   * Describe your question, issue, or request in detail.
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  type: 'question' | 'feature-request' | 'bug' | 'onboarding' | 'other';
  status: 'open' | 'in-progress' | 'waiting-on-vendor' | 'waiting-on-admin' | 'closed';
  priority: 'low' | 'normal' | 'high' | 'urgent';
  /**
   * Vendor associated with this task.
   */
  vendor: string | Vendor;
  createdBy: string | User;
  /**
   * Admin/BDO responsible for this task.
   */
  assignedTo?: (string | null) | User;
  /**
   * Optional tags, e.g. 'category', 'upload-help', 'payments'.
   */
  tags?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  visibility: 'vendor-and-admin' | 'admin-only';
  closedAt?: string | null;
  lastReadAtByVendor?: string | null;
  /**
   * Map of admin user IDs to last read timestamps.
   */
  lastReadAtByAdmin?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages and notes attached to vendor tasks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-task-messages".
 */
export interface VendorTaskMessage {
  id: string;
  task: string | VendorTask;
  author: string | User;
  role: 'vendor' | 'admin';
  /**
   * Message content.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  attachments?: (string | Media)[] | null;
  /**
   * When checked, this note is visible only to admins/BDOs.
   */
  isInternal?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-hero-banners".
 */
export interface VendorHeroBanner {
  id: string;
  /**
   * The vendor who owns this banner
   */
  vendor: string | Vendor;
  /**
   * Title for the hero banner section
   */
  title: string;
  /**
   * Optional subtitle text
   */
  subtitle?: string | null;
  /**
   * Optional background image for the banner (recommended: 1920x500px)
   */
  backgroundImage?: (string | null) | Media;
  /**
   * Select products to display in this hero banner (only your own products)
   */
  products: (string | Product)[];
  /**
   * Only active banners will be displayed on your vendor page
   */
  isActive?: boolean | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'hero-banners';
        value: string | HeroBanner;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'vendors';
        value: string | Vendor;
      } | null)
    | ({
        relationTo: 'roles';
        value: string | Role;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'variant-types';
        value: string | VariantType;
      } | null)
    | ({
        relationTo: 'variant-options';
        value: string | VariantOption;
      } | null)
    | ({
        relationTo: 'vendor-tasks';
        value: string | VendorTask;
      } | null)
    | ({
        relationTo: 'vendor-task-messages';
        value: string | VendorTaskMessage;
      } | null)
    | ({
        relationTo: 'vendor-hero-banners';
        value: string | VendorHeroBanner;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  name?: T;
  roles?: T;
  vendor?: T;
  vendorRole?: T;
  appRole?: T;
  oauthProviders?:
    | T
    | {
        google?:
          | T
          | {
              id?: T;
              email?: T;
            };
        facebook?:
          | T
          | {
              id?: T;
              email?: T;
            };
      };
  profilePicture?: T;
  shippingAddresses?:
    | T
    | {
        label?: T;
        isDefault?: T;
        fullName?: T;
        phone?: T;
        street?: T;
        city?: T;
        state?: T;
        zipcode?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  color?: T;
  parent?: T;
  subcategories?: T;
  variantConfig?:
    | T
    | {
        requiredVariants?: T;
        optionalVariants?: T;
        variantOptions?: T;
        pricingRules?:
          | T
          | {
              basePrice?: T;
              sizeOverrides?: T;
              colorOverrides?: T;
              materialOverrides?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  price?: T;
  vendor?: T;
  category?: T;
  subcategory?: T;
  image?: T;
  cover?: T;
  videoSource?: T;
  video?: T;
  youtubeUrl?: T;
  youtubeVideoId?: T;
  youtubeStartTime?: T;
  youtubeStartTimeSeconds?: T;
  refundPolicy?: T;
  content?: T;
  isPrivate?: T;
  isArchived?: T;
  tags?: T;
  variants?:
    | T
    | {
        variantData?: T;
        stock?: T;
        price?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-banners_select".
 */
export interface HeroBannersSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  backgroundImage?: T;
  products?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  name?: T;
  user?: T;
  vendor?: T;
  product?: T;
  status?: T;
  statusHistory?:
    | T
    | {
        status?: T;
        timestamp?: T;
        note?: T;
        id?: T;
      };
  total?: T;
  commission?: T;
  commissionRate?: T;
  quantity?: T;
  size?: T;
  color?: T;
  stripeCheckoutSessionId?: T;
  stripeAccountId?: T;
  stripePaymentIntentId?: T;
  stripeTransferId?: T;
  transferStatus?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  offlinePaymentContact?:
    | T
    | {
        phone?: T;
        email?: T;
        customerPhone?: T;
      };
  offlinePaymentNotes?: T;
  shippingAddress?:
    | T
    | {
        fullName?: T;
        phone?: T;
        street?: T;
        city?: T;
        state?: T;
        zipcode?: T;
        country?: T;
      };
  shippingMethod?: T;
  shippingCost?: T;
  shippingStatus?: T;
  trackingNumber?: T;
  carrier?: T;
  trackingUrl?: T;
  estimatedDelivery?: T;
  actualDeliveryDate?: T;
  shippingLabelUrl?: T;
  packageWeight?: T;
  packageDimensions?:
    | T
    | {
        length?: T;
        width?: T;
        height?: T;
      };
  insuranceValue?: T;
  vendorPayout?:
    | T
    | {
        amount?: T;
        commissionAmount?: T;
        status?: T;
        payoutDate?: T;
        transactionId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors_select".
 */
export interface VendorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  logo?: T;
  coverImage?: T;
  heroBanner?:
    | T
    | {
        title?: T;
        subtitle?: T;
        backgroundImage?: T;
        products?: T;
        isActive?: T;
        order?: T;
      };
  email?: T;
  phone?: T;
  website?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zipcode?: T;
        country?: T;
      };
  approveAction?: T;
  status?: T;
  isActive?: T;
  stripeAccountId?: T;
  stripeAccountStatus?: T;
  stripeOnboardingLink?: T;
  stripeOnboardingCompleted?: T;
  stripeAccountDetails?: T;
  stripeAccountCountry?: T;
  stripeAccountEmail?: T;
  stripeChargesEnabled?: T;
  stripePayoutsEnabled?: T;
  syncStripeAction?: T;
  commissionRate?: T;
  contactPhone?: T;
  contactEmail?: T;
  preferredPaymentMethod?: T;
  offlinePaymentInstructions?: T;
  verificationDocuments?:
    | T
    | {
        document?: T;
        type?: T;
        notes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  description?: T;
  permissions?:
    | T
    | {
        permission?: T;
        id?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  email?: T;
  phone?: T;
  vendors?: T;
  totalOrders?: T;
  totalSpent?: T;
  lastOrderDate?: T;
  firstOrderDate?: T;
  tags?:
    | T
    | {
        tag?: T;
        vendor?: T;
        id?: T;
      };
  notes?:
    | T
    | {
        text?: T;
        vendor?: T;
        createdBy?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variant-types_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  unit?: T;
  displayOrder?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variant-options_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  value?: T;
  label?: T;
  variantType?: T;
  category?: T;
  hexCode?: T;
  image?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-tasks_select".
 */
export interface VendorTasksSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  type?: T;
  status?: T;
  priority?: T;
  vendor?: T;
  createdBy?: T;
  assignedTo?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  visibility?: T;
  closedAt?: T;
  lastReadAtByVendor?: T;
  lastReadAtByAdmin?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-task-messages_select".
 */
export interface VendorTaskMessagesSelect<T extends boolean = true> {
  task?: T;
  author?: T;
  role?: T;
  body?: T;
  attachments?: T;
  isInternal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-hero-banners_select".
 */
export interface VendorHeroBannersSelect<T extends boolean = true> {
  vendor?: T;
  title?: T;
  subtitle?: T;
  backgroundImage?: T;
  products?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}