/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    tags: Tag;
    'hero-banners': HeroBanner;
    orders: Order;
    vendors: Vendor;
    roles: Role;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      subcategories: 'categories';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'hero-banners': HeroBannersSelect<false> | HeroBannersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    vendors: VendorsSelect<false> | VendorsSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  username?: string | null;
  name?: string | null;
  /**
   * ⚠️ DEPRECATED: Use appRole and vendorRole instead. Kept for backward compatibility.
   */
  roles?: ('super-admin' | 'user')[] | null;
  /**
   * The vendor/shop this user belongs to. Required for all users except App Admins.
   */
  vendor?: (string | null) | Vendor;
  /**
   * Role within the vendor organization (e.g., Vendor Owner, Vendor Manager, Vendor Staff)
   */
  vendorRole?: (string | null) | Role;
  /**
   * Application-level role (e.g., App Admin, App Support, Customer). App Admin does not require a vendor.
   */
  appRole?: (string | null) | Role;
  oauthProviders?: {
    google?: {
      id?: string | null;
      email?: string | null;
    };
    facebook?: {
      id?: string | null;
      email?: string | null;
    };
  };
  profilePicture?: string | null;
  /**
   * Manage multiple shipping addresses. Set one as default for faster checkout.
   */
  shippingAddresses?:
    | {
        /**
         * e.g., Home, Work, Office
         */
        label: string;
        /**
         * Set as default shipping address
         */
        isDefault?: boolean | null;
        /**
         * Recipient's full name
         */
        fullName: string;
        /**
         * Contact phone number (e.g., +1-555-123-4567)
         */
        phone: string;
        /**
         * Street address, apartment, suite, etc.
         */
        street: string;
        city: string;
        state:
          | 'AL'
          | 'AK'
          | 'AZ'
          | 'AR'
          | 'CA'
          | 'CO'
          | 'CT'
          | 'DE'
          | 'FL'
          | 'GA'
          | 'HI'
          | 'ID'
          | 'IL'
          | 'IN'
          | 'IA'
          | 'KS'
          | 'KY'
          | 'LA'
          | 'ME'
          | 'MD'
          | 'MA'
          | 'MI'
          | 'MN'
          | 'MS'
          | 'MO'
          | 'MT'
          | 'NE'
          | 'NV'
          | 'NH'
          | 'NJ'
          | 'NM'
          | 'NY'
          | 'NC'
          | 'ND'
          | 'OH'
          | 'OK'
          | 'OR'
          | 'PA'
          | 'RI'
          | 'SC'
          | 'SD'
          | 'TN'
          | 'TX'
          | 'UT'
          | 'VT'
          | 'VA'
          | 'WA'
          | 'WV'
          | 'WI'
          | 'WY'
          | 'DC';
        /**
         * 5-digit ZIP code or ZIP+4 format (e.g., 12345 or 12345-6789)
         */
        zipcode: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Vendors/Sellers in the marketplace
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors".
 */
export interface Vendor {
  id: string;
  /**
   * Business/Vendor name
   */
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name)
   */
  slug: string;
  /**
   * Vendor description/bio
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Vendor logo image
   */
  logo?: (string | null) | Media;
  /**
   * Vendor cover/banner image
   */
  coverImage?: (string | null) | Media;
  /**
   * Business email address
   */
  email: string;
  /**
   * Business phone number
   */
  phone?: string | null;
  /**
   * Business website URL
   */
  website?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zipcode?: string | null;
    country?: string | null;
  };
  /**
   * Quick action to approve and activate this vendor
   */
  approveAction?: string | null;
  /**
   * Vendor approval status. Use 'Approve & Activate' button to approve vendors.
   */
  status?: ('pending' | 'approved' | 'suspended' | 'rejected') | null;
  /**
   * Active vendors can sell products. Use 'Approve & Activate' button above to activate vendors.
   */
  isActive?: boolean | null;
  /**
   * Stripe Connect account ID for payouts
   */
  stripeAccountId?: string | null;
  /**
   * Platform commission rate (%)
   */
  commissionRate?: number | null;
  /**
   * Business verification documents (business license, tax ID, etc.)
   */
  verificationDocuments?:
    | {
        document: string | Media;
        type: 'business-license' | 'tax-id' | 'identity' | 'other';
        /**
         * Additional notes about this document
         */
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Application and vendor-level roles for user permissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: string;
  /**
   * Role name (e.g., 'Vendor Owner', 'App Admin')
   */
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name)
   */
  slug: string;
  /**
   * Role type: Application roles are for app-level access, Vendor roles are for vendor organization access
   */
  type: 'app' | 'vendor';
  /**
   * Description of what this role allows
   */
  description?: string | null;
  /**
   * List of permissions granted by this role
   */
  permissions?:
    | {
        /**
         * Permission name (e.g., 'manage-products', 'view-orders')
         */
        permission: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Active roles can be assigned to users
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug: string;
  color?: string | null;
  parent?: (string | null) | Category;
  subcategories?: {
    docs?: (string | Category)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * You must verify your account before creating products
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Price in USD
   */
  price: number;
  /**
   * The vendor/shop that owns this product
   */
  vendor: string | Vendor;
  /**
   * Select a category for this product
   */
  category: string | Category;
  /**
   * Select a subcategory for this product (optional)
   */
  subcategory?: (string | null) | Category;
  image?: (string | null) | Media;
  cover?: (string | null) | Media;
  refundPolicy?: ('30-day' | '14-day' | '7-day' | '3-day' | '1-day' | 'no-refunds') | null;
  /**
   * Protected content only visible to customers after purchase. Add product documentation, downloadable files, getting started guides, and bonus materials. Supports Markdown formatting
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * If checked, this product will not be shown on the public storefront
   */
  isPrivate?: boolean | null;
  /**
   * If checked, this product will be archived
   */
  isArchived?: boolean | null;
  /**
   * Select tags for this product
   */
  tags?: (string | Tag)[] | null;
  /**
   * Add size and color variants with inventory and price adjustments. Leave empty if product has no variants.
   */
  variants?:
    | {
        /**
         * Size variant (optional if using color only)
         */
        size?: ('XS' | 'S' | 'M' | 'L' | 'XL' | 'XXL') | null;
        /**
         * Color variant (e.g., Red, Blue, Black) - optional if using size only
         */
        color?: string | null;
        /**
         * Available inventory for this variant
         */
        stock: number;
        /**
         * Price for this specific variant. If not set, uses the product's base price. Each size/color combination can have its own price.
         */
        price?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name: string;
  products?: (string | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-banners".
 */
export interface HeroBanner {
  id: string;
  /**
   * Title for the hero banner section
   */
  title: string;
  /**
   * Optional subtitle text
   */
  subtitle?: string | null;
  /**
   * Optional background image for the banner
   */
  backgroundImage?: (string | null) | Media;
  /**
   * Select products to display in this hero banner
   */
  products: (string | Product)[];
  /**
   * Only active banners will be displayed on the homepage
   */
  isActive?: boolean | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  /**
   * Unique order number (auto-generated)
   */
  orderNumber: string;
  name: string;
  user: string | User;
  /**
   * Vendor that should fulfill this order (auto-assigned from product)
   */
  vendor: string | Vendor;
  product: string | Product;
  /**
   * Order status workflow: Pending → Payment Done → Processing → Complete
   */
  status: 'pending' | 'payment_done' | 'processing' | 'complete' | 'canceled' | 'refunded';
  /**
   * History of status changes
   */
  statusHistory?:
    | {
        status?: ('pending' | 'payment_done' | 'processing' | 'complete' | 'canceled' | 'refunded') | null;
        timestamp?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Total order amount in USD
   */
  total: number;
  /**
   * Quantity of items ordered
   */
  quantity: number;
  /**
   * Product size variant (if applicable)
   */
  size?: string | null;
  /**
   * Product color variant (if applicable)
   */
  color?: string | null;
  /**
   * Stripe checkout session associated with the order
   */
  stripeCheckoutSessionId: string;
  /**
   * Stripe account associated with the order
   */
  stripeAccountId?: string | null;
  /**
   * Stripe payment intent ID
   */
  stripePaymentIntentId?: string | null;
  /**
   * Shipping tracking number
   */
  trackingNumber?: string | null;
  /**
   * Shipping carrier
   */
  carrier?: ('usps' | 'fedex' | 'ups' | 'dhl' | 'other') | null;
  /**
   * Tracking URL (auto-generated if carrier is selected)
   */
  trackingUrl?: string | null;
  /**
   * Estimated delivery date
   */
  estimatedDelivery?: string | null;
  /**
   * Payout details for the vendor
   */
  vendorPayout?: {
    /**
     * Amount to be paid to vendor (after commission)
     */
    amount?: number | null;
    /**
     * Platform commission amount
     */
    commissionAmount?: number | null;
    /**
     * Payout status
     */
    status?: ('pending' | 'processing' | 'completed' | 'failed') | null;
    /**
     * Date when payout was processed
     */
    payoutDate?: string | null;
    /**
     * Stripe transfer/payout transaction ID
     */
    transactionId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'hero-banners';
        value: string | HeroBanner;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'vendors';
        value: string | Vendor;
      } | null)
    | ({
        relationTo: 'roles';
        value: string | Role;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  name?: T;
  roles?: T;
  vendor?: T;
  vendorRole?: T;
  appRole?: T;
  oauthProviders?:
    | T
    | {
        google?:
          | T
          | {
              id?: T;
              email?: T;
            };
        facebook?:
          | T
          | {
              id?: T;
              email?: T;
            };
      };
  profilePicture?: T;
  shippingAddresses?:
    | T
    | {
        label?: T;
        isDefault?: T;
        fullName?: T;
        phone?: T;
        street?: T;
        city?: T;
        state?: T;
        zipcode?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  color?: T;
  parent?: T;
  subcategories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  price?: T;
  vendor?: T;
  category?: T;
  subcategory?: T;
  image?: T;
  cover?: T;
  refundPolicy?: T;
  content?: T;
  isPrivate?: T;
  isArchived?: T;
  tags?: T;
  variants?:
    | T
    | {
        size?: T;
        color?: T;
        stock?: T;
        price?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-banners_select".
 */
export interface HeroBannersSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  backgroundImage?: T;
  products?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  name?: T;
  user?: T;
  vendor?: T;
  product?: T;
  status?: T;
  statusHistory?:
    | T
    | {
        status?: T;
        timestamp?: T;
        note?: T;
        id?: T;
      };
  total?: T;
  quantity?: T;
  size?: T;
  color?: T;
  stripeCheckoutSessionId?: T;
  stripeAccountId?: T;
  stripePaymentIntentId?: T;
  trackingNumber?: T;
  carrier?: T;
  trackingUrl?: T;
  estimatedDelivery?: T;
  vendorPayout?:
    | T
    | {
        amount?: T;
        commissionAmount?: T;
        status?: T;
        payoutDate?: T;
        transactionId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors_select".
 */
export interface VendorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  logo?: T;
  coverImage?: T;
  email?: T;
  phone?: T;
  website?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zipcode?: T;
        country?: T;
      };
  approveAction?: T;
  status?: T;
  isActive?: T;
  stripeAccountId?: T;
  commissionRate?: T;
  verificationDocuments?:
    | T
    | {
        document?: T;
        type?: T;
        notes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  description?: T;
  permissions?:
    | T
    | {
        permission?: T;
        id?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}